//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrossTasksTags
    {
        public Nullable<int> TaskId { get; set; }
        public Nullable<int> TagsId { get; set; }
        public int Id { get; set; }
    
        public virtual Tags Tags { get; set; }
        public virtual Tasks Tasks { get; set; }
    }
}
