//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tags
    {
        public Tags()
        {
            this.CrossTasksTags = new HashSet<CrossTasksTags>();
        }
    
        public int Id { get; set; }
        public string TitleTag { get; set; }
    
        public virtual ICollection<CrossTasksTags> CrossTasksTags { get; set; }
    }
}
