//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace TaskManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int TaskId { get; set; }
        [Required(ErrorMessage = "Пожалуйста заполните поле 'Название'", AllowEmptyStrings = false)]
        public string Title { get; set; }
        [Required(ErrorMessage = "Пожалуйста укажите 'deadline'", AllowEmptyStrings = false)]
        public System.DateTime TaskTerm { get; set; }
        [Required(ErrorMessage = "Пожалуйста укажите хотя бы один 'тег'", AllowEmptyStrings = false)]
        public string Tags { get; set; }
        [Required(ErrorMessage = "Пожалуйста заполните поле 'Описание'", AllowEmptyStrings = false)]
        public string Description { get; set; }
        public Nullable<int> UsId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string StatusString { get; set; }
    
        public virtual Statuses Statuses { get; set; }
        public virtual Users Users { get; set; }
    }
}

