//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace TaskManager
{
    using System;
    using System.Collections.Generic;

    public partial class USERS
    {
        public USERS()
        {
            this.TASKS = new HashSet<TASKS>();
        }

        public int USERID { get; set; }

        [Required(ErrorMessage = "Пожалуйста введите Имя", AllowEmptyStrings = false)]
        [Display(Name = "Имя")]
        public string FIRST_NAME { get; set; }
        [Required(ErrorMessage = "Пожалуйста введите Фамилию", AllowEmptyStrings = false)]
        [Display(Name = "Фамилия")]
        public string LAST_NAME { get; set; }
        [RegularExpression(@"^([0-9a-zA-Z]([\+\-_\.][0-9a-zA-Z]+)*)+@(([0-9a-zA-Z][-\w]*[0-9a-zA-Z]*\.)+[a-zA-Z0-9]{2,3})$", ErrorMessage = "Введенный Email не коректен")]
        [Display(Name = "Email")]
        public string EMAIL { get; set; }
        [Required(ErrorMessage = "Пожалуйста введите Логин", AllowEmptyStrings = false)]
        [StringLength(15, MinimumLength = 4, ErrorMessage = "Логин должен иметь минимум 4 символа")]
        [Display(Name = "Логин")]
        public string LOGIN_NAME { get; set; }
        [Required(ErrorMessage = "Пожалуйста введите Пароль", AllowEmptyStrings = false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        [StringLength(70, MinimumLength = 3, ErrorMessage = "Пароль должен состоять как минимум из 3-х символов")]
        [Display(Name = "Пароль")]
        public string PASS { get; set; }
        [Required(ErrorMessage = "Пожалуйста введите Подтверждение пароля", AllowEmptyStrings = false)]
        [Compare("PASS", ErrorMessage = "Пароль не совподает")]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        [Display(Name = "Подтверждение")]
        public string PASSConfirm { get; set; }
        public string CONFIRM { get; set; }
        [Required(ErrorMessage = "Пожалуйста введите Капчу", AllowEmptyStrings = false)]
        [StringLength(15, MinimumLength = 5, ErrorMessage = "Капча должен иметь минимум 5 символов")]
        [Display(Name = "Капча")]
        public string CAPCHA { get; set; }

        public virtual ICollection<TASKS> TASKS { get; set; }
    }
}
